name: Dependency Tree

on:
  pull_request_target:
    branches:
      - master
env:
  # The modules to check for dependencies. If there is more than one they are comma separated
  MODULES_TO_CHECK: core-feature-pack
  # The name of the labels to use if the dependencies are ok
  DEPS_OK_LABEL_NAME: deps-ok
  # The name of the labels to use if the dependencies changed
  DEPS_CHANGED_LABEL_NAME: deps-changed
  # People/teams to mention in the PR comment if dependencies changed
  CHANGE_MENTIONS: @wildfly/prod
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone base version
        uses: actions/checkout@v2
        with:
          ref: $(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
          path: base

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      # Run the caching against the base version only
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clone PR version
        uses: actions/checkout@v2
        with:
          path: pr

      - name: Build base
        working-directory: base
        run: |
          mvn -B install -DskipTests

      - name: Build PR
        working-directory: pr
        run: |
          mvn -B install -DskipTests

      - name: Check versions
        uses: wildfly/dep-tree-diff-action@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          modules: ${MODULES_TO_CHECK}
          deps-ok-label: ${DEPS_OK_LABEL_NAME}
          deps-changed-label: ${DEPS_CHANGED_LABEL_NAME}
          tool-change-mentions: ${CHANGE_MENTIONS}